# -*- coding: utf-8 -*-
"""CRNNMAIN (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17kkqK4cS95B1n4EvgbJNfJepnl-I1Fmd
"""

# Install kaggle API
!pip install kaggle api

# Upload your kaggle.json before running this cell (in Colab: "Files" → upload)
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

# Download and unzip dataset
!kaggle datasets download -d eliasmarcon/environmental-sound-classification-50
!unzip -q environmental-sound-classification-50.zip -d esc50

pip install numpy pandas librosa scikit-learn matplotlib seaborn tensorflow tqdm

import os
import numpy as np
import pandas as pd
import librosa
import librosa.display
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm
import tensorflow as tf
from tensorflow.keras import layers, models, regularizers
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping

# Paths
audio_dir = "esc50/ESC-50-master/wav_files"
label_file = "esc50/ESC-50-master/esc50_labels.csv"

# Load metadata
df = pd.read_csv(label_file)
label_encoder = LabelEncoder()
df['label_idx'] = label_encoder.fit_transform(df['category'])
num_classes = len(label_encoder.classes_)

# -------------------- Audio Augmentation --------------------
def augment_audio(y, sr):
    if np.random.rand() < 0.3:
        y = y + 0.005 * np.random.randn(len(y))  # noise
    if np.random.rand() < 0.3:
        y = librosa.effects.pitch_shift(y=y, sr=sr, n_steps=np.random.randint(-2, 3))
    if np.random.rand() < 0.3:
        y = librosa.effects.time_stretch(y, rate=np.random.uniform(0.8, 1.2))
    return y

# -------------------- Feature Extraction --------------------
def extract_mel_spectrogram(file_path, augment=False):
    y, sr = librosa.load(file_path, sr=22050)
    if augment:
        y = augment_audio(y, sr)
    S = librosa.feature.melspectrogram(y=y, sr=sr, n_mels=128)
    log_S = librosa.power_to_db(S, ref=np.max)
    log_S = librosa.util.fix_length(log_S, size=216, axis=1)
    log_S = librosa.util.normalize(log_S)
    return log_S.T[..., np.newaxis]  # (216, 128, 1)

# -------------------- Load Dataset --------------------
X, y = [], []
print("🔍 Extracting features...")
for _, row in tqdm(df.iterrows(), total=len(df)):
    path = os.path.join(audio_dir, row['filename'])
    try:
        for i in range(2):  # original + one augmentation
            features = extract_mel_spectrogram(path, augment=(i == 1))
            X.append(features)
            y.append(row['label_idx'])
    except Exception as e:
        print(f"Error with {row['filename']}: {e}")

X = np.array(X)
y = to_categorical(y, num_classes)
print(f"✅ Data shape: {X.shape}, Labels: {y.shape}")

# -------------------- Split --------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# -------------------- Attention Layer --------------------
class Attention(tf.keras.layers.Layer):
    def __init__(self):
        super().__init__()

    def build(self, input_shape):
        self.W = self.add_weight(name='att_weight', shape=(input_shape[-1], 1),
                                 initializer='glorot_uniform', trainable=True)
        self.b = self.add_weight(name='att_bias', shape=(input_shape[1], 1),
                                 initializer='zeros', trainable=True)
        super().build(input_shape)

    def call(self, x):
        e = tf.keras.backend.tanh(tf.keras.backend.dot(x, self.W) + self.b)
        a = tf.keras.backend.softmax(e, axis=1)
        output = x * a
        return tf.keras.backend.sum(output, axis=1)

# -------------------- Build CRNN Model --------------------
def build_crnn(input_shape, num_classes):
    inp = layers.Input(shape=input_shape)

    x = layers.Conv2D(32, (3, 3), padding='same', activation='relu',
                      kernel_regularizer=regularizers.l2(1e-4))(inp)
    x = layers.BatchNormalization()(x)
    x = layers.MaxPooling2D((2, 2))(x)

    x = layers.Conv2D(64, (3, 3), padding='same', activation='relu',
                      kernel_regularizer=regularizers.l2(1e-4))(x)
    x = layers.BatchNormalization()(x)
    x = layers.MaxPooling2D((2, 2))(x)

    x = layers.Dropout(0.3)(x)
    x = layers.Reshape((x.shape[1], x.shape[2] * x.shape[3]))(x)

    x = layers.Bidirectional(layers.GRU(64, return_sequences=True))(x)
    x = layers.Dropout(0.3)(x)

    x = Attention()(x)
    x = layers.Dense(64, activation='relu')(x)
    x = layers.Dropout(0.4)(x)

    out = layers.Dense(num_classes, activation='softmax')(x)

    return models.Model(inputs=inp, outputs=out)

# -------------------- Train Model --------------------
input_shape = (216, 128, 1)
model = build_crnn(input_shape, num_classes)
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

callbacks = [
    ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, verbose=1),
    EarlyStopping(monitor='val_loss', patience=7, restore_best_weights=True)
]

history = model.fit(
    X_train, y_train,
    validation_split=0.15,
    epochs=50,
    batch_size=32,
    callbacks=callbacks,
    verbose=1
)

# -------------------- Evaluate --------------------
loss, acc = model.evaluate(X_test, y_test)
print(f"\n✅ Final Test Accuracy: {acc:.2%}")

# -------------------- Report & Confusion Matrix --------------------
y_pred = model.predict(X_test)
y_pred_labels = np.argmax(y_pred, axis=1)
y_true_labels = np.argmax(y_test, axis=1)

# Confusion matrix
cm = confusion_matrix(y_true_labels, y_pred_labels)
plt.figure(figsize=(12, 10))
sns.heatmap(cm, cmap='Blues', xticklabels=label_encoder.classes_, yticklabels=label_encoder.classes_, square=True)
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.tight_layout()
plt.show()

# Classification report
print(classification_report(y_true_labels, y_pred_labels, target_names=label_encoder.classes_))

# Save the model
model.save("esc50_crnn_model.h5")
print("✅ Model saved as 'esc50_crnn_model.h5'")

import pickle

# Save the label encoder
with open("label_encoder.pkl", "wb") as f:
    pickle.dump(label_encoder, f)
print("✅ Label encoder saved as 'label_encoder.pkl'")

# Save training history
with open("training_history.pkl", "wb") as f:
    pickle.dump(history.history, f)
print("✅ Training history saved as 'training_history.pkl'")

import numpy as np
import librosa
import pickle
from tensorflow.keras.models import load_model
from tensorflow.keras.layers import Layer
import tensorflow.keras.backend as K

# -------------------- Custom Attention Layer --------------------
class Attention(Layer):
    def build(self, input_shape):
        self.W = self.add_weight(name='att_weight', shape=(input_shape[-1], 1),
                                 initializer='glorot_uniform', trainable=True)
        self.b = self.add_weight(name='att_bias', shape=(input_shape[1], 1),
                                 initializer='zeros', trainable=True)
        super().build(input_shape)

    def call(self, x):
        e = K.tanh(K.dot(x, self.W) + self.b)
        a = K.softmax(e, axis=1)
        output = x * a
        return K.sum(output, axis=1)

# -------------------- Load Model and Label Encoder --------------------
model = load_model("esc50_crnn_model.h5", custom_objects={'Attention': Attention})
with open("label_encoder.pkl", "rb") as f:
    label_encoder = pickle.load(f)

# -------------------- Feature Extraction --------------------
def extract_mel_spectrogram(file_path):
    y, sr = librosa.load(file_path, sr=22050)
    S = librosa.feature.melspectrogram(y=y, sr=sr, n_mels=128)
    log_S = librosa.power_to_db(S, ref=np.max)
    log_S = librosa.util.fix_length(log_S, size=216, axis=1)
    log_S = librosa.util.normalize(log_S)
    return log_S.T[..., np.newaxis]  # Shape: (216, 128, 1)

# -------------------- Predict Function --------------------
def predict_audio(file_path):
    features = extract_mel_spectrogram(file_path)
    features = np.expand_dims(features, axis=0)  # Add batch dimension
    predictions = model.predict(features)
    predicted_index = np.argmax(predictions, axis=1)[0]
    predicted_label = label_encoder.inverse_transform([predicted_index])[0]
    print(f"🔊 Predicted label: {predicted_label}")

# -------------------- Run Prediction --------------------
# Replace with your own file path
predict_audio("siren.mp3")